//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice6.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UchPracticeDBEntities : DbContext
    {
        private static UchPracticeDBEntities _context;
        public UchPracticeDBEntities()
            : base("name=UchPracticeDBEntities")
        {
        }

        public static UchPracticeDBEntities GetContext()
        {
            if (_context == null)
            {
                _context = new UchPracticeDBEntities();
            }

            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Correspondents> Correspondents { get; set; }
        public virtual DbSet<DocTable> DocTable { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
