//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocTable
    {
        public int Id { get; set; }
        public string DocumentName { get; set; }
        public int FK_Orders { get; set; }
        public int FK_Correspondent { get; set; }
    
        public virtual Correspondents Correspondents { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
